### PR TITLE
Allow separate parallelization parameters for "correct batch effect" and other phases

### PR DESCRIPTION
**Pull request by t-carroll**
In my implementation of run.Ted() (Rstudio on interactive node of Scientific Linux-based cluster), I notice that the "correct batch effect" phase of run.Ted() draws a lot more CPU than the "run first sampling" or "run final sampling" phases. For instance, even running with just n.cores = 3 on a cluster node with 32 available cores, enough CPU power is used by run.Ted() during this phase that the load raises high enough (>70 on our cluster) to send the entire node into an alarm state. The load raises precipitously with higher n.cores in this phase. However, during the other phases (first and final sampling), the load remains quite small (~5-6), even with many more cores (n.cores =12).

To allow for quick sampling and to minimize the load during the correct batch effect phase, I have modified this function to allow for a seperate parameter which specifies the number of cores for the batch effect phase (n.cores.batch) in addition to the n.cores parameter- For instance I can use run.Ted() with n.cores = 12 and n.cores.batch = 2, which seems to work well for my setup. I have constructed this so n.cores.batch defaults to the value of n.cores if it is not specified by the user, so the default usage need not change for setups where this modification is not needed.

I am not sure why the CPU load differs so much in my use case, and I'm wondering whether it's specific to my setup- perhaps something to do with running it on a qrsh node from Rstudio. In any case, I've found these changes very useful for my set-up, and figured I'd generate a pull request in case you wanted to merge it into your code as well. Or if this is only a problem on my set-up I'll just keep it on my fork :)

### CODE REVIEW

**Comment by tinyi** [comment]
Hi. Thank you very much for your feedback. When you say "the CPU load", do
you mean %of CPU usage over all cores?  Sampling and batch correction shall
use the same number of threads as specified by n.cores. Higher average CPU
usage is expected for the batch correction phase, due to the more
continuous nature of optimization. If the number of threads used are
consistent, I would not be worried.

In general, I would recommend running the command line mode. Rstudio tends
to use lots of extra memories, which I often found much less efficient than
the command line mode.

Best,

Tinyi

**Comment by t-carroll** [comment]
Hi Tinyi,

I'm referring to "load_avg" from qstat -f, as opposed to the % CPU usage from something like top. However this metric is cluster specific and may not be that useful for you, but I just mention it because when the load is too high the whole node goes into an alarm state, which is undesirable. When I look at top during the batch correction phase, the 2 cores I use are at ~1300% CPU usage, as opposed to ~100% for the other phases.

I will see if I can get a better graphical representation of what's going on here, and will try it with command line R to see if that helps when I have some time!

Thanks,
Tom

**Comment by tinyi** [comment]
Hi Tom,

Thanks for providing me with the information. This is a bit unexpected, as
I have never run into issues where the mclapply function from the parallel
package uses more than 100% per thread. I suspect this might be platform
specific. I tested everything on R 3.5.1. Not sure if this is related to
the version of R.

Best,

Tinyi

**Comment by t-carroll** [comment]
Hi Tinyi,

Just a few notes from my troubleshooting:

On R 3.6.1:
1. Following the above suggestions, I tried running the same commands on R (command line) that I ran in Rstudio, but saw about the same CPU usage during batch effect phase (~1500%)
2. Subsetting the X from 80 samples down to 5 did not change this, suggesting it's not dependent on the dimensions of X
3. I subsetted my input scRNA reference dataset, which is quite large (~30,000x30,000) down to a size similar to your reference data (~200x20000). This also did not solve the problem.

On R 3.5.1
1. Tried switching to R 3.5.1 to see if this fixed the problem. Unfortunately I still encounter the same issue both on command line R and Rstudio, although with slightly less CPU usage (~1000%)

I am running R environments installed via conda on a linux based cluster (interactive compute node).

I see a few statements in runTed.R and embedding_learning.R where n.cores is set to 40 (run.EM in embedding_learning and run.gibbs.individualPhi in runTed.R); could that have something to do with it? I don't believe either of those are called during the batch correct phase, however, and presumably the n.cores argument would be superceded by what we're specifying on the command line. So not sure what else could be going on here- I'm not that familiar with mclapply/parallelization generally! 

I am happy to close out this pull request (although I'll probably use my fork to prevent the cluster alarming) unless there's anything else you want me to try- just let me know if so.

Well done on the package, btw- looking great in internal benchmarking thus far!

-Tom

**Comment by t-carroll** [comment]
closing as functions as run.Ted function is now updated

**Pull request closed without merging**
